#!/bin/dash

directory=".legit"

indexdir="$directory/index"





if [ ! -d "$directory" ]
then
	echo "legit-add: error: no .legit directory containing legit repository exists"
	exit 1
fi

#check the branch

currentbranch=`cat "$directory/branches.txt" | tail -n1`

if [ "$currentbranch" != "master" ]
then
	indexdir="$directory/.branch/$currentbranch/index"
fi


#invalid input number
if [ $# -eq 0 ]
then
	echo "usage: legit-add <filenames>"
	exit 1;

fi

#check valid name
for file in "$@"
do	

	if echo "$file" |egrep -q '^\-.+'
	then
		echo "usage: legit-add <filenames>"
		exit 1
	fi

	if [ "$file" = "" ]
	then
		echo "legit-add: error: invalid filename '$file'"
		exit 1
	fi

	if echo "$file" | egrep -q "^[^a-zA-Z0-9]"
	then
		echo "legit-add: error: invalid filename '$file'"
		exit 1
	fi

	if echo "$file" | egrep -q "[^a-zA-Z0-9\._\-]"
	then
		echo "legit-add: error: invalid filename '$file'"	
		exit 1
	fi
done


#check exist and regualr file 

for file in $@	
do
	if [ -e $file ]
	then
		if [ ! -f $file ]
		then
			echo "legit-add: error: '$file' is not a regular file"
			exit 1
		fi

	else
		if [ ! -d $indexdir ]
		then
			echo "legit-add: error: can not open '$file'"
			exit 1
		fi

		string=`find $indexdir -name $file`

		if [ "$string" = "" ]
		then
			echo "legit-add: error: can not open '$file'"
			exit 1

		fi	
			

	fi

done


			



mkdir -p "$directory"/index

for file in $@
do


#check it exist in the index, if yes, it can be rm in the index.
	
	if [ ! -e $file ]
	then
		string=`find $indexdir -name $file`
		if [ "$string" != "" ]
		then
			rm -f $indexdir/$file
		fi
	else
		cp "$file" "$indexdir"
	fi			
done







