#!/bin/dash

directory=".legit"
place="$directory/.commit"
log="$directory/number.txt"
indexdir="$directory/index"

if [ ! -d $directory ]
then

	echo "legit-show: error: no .legit directory containing legit repository exists"
	exit 1
fi

if [ ! -d "$place" ]
then
	echo "legit-show: error: your repository does not have any commits yet"
	exit 1
fi	

if [ $# -ne 1 ]
then
	echo "usage: legit-show <commit>:<filename>"
	exit 1
fi


#check the branch

currentbranch=`cat "$directory/branches.txt" | tail -n1`

if [ "$currentbranch" != "master" ]
then
	indexdir="$directory/.branch/$currentbranch/index"
fi





#file is the filename, version is the commit number

if echo "$1" |egrep -q ':'
then
	version=`echo "$1"|cut -d ':' -f1`
	file=`echo "$1"|cut -d ':' -f2`
	lastestversion=`cat $log | tail -n1 | cut -d '-' -f1`

#check commit version
	if [ "$version" = "" ]
	then
		if [ "$file" = "" ]
		then
			echo "legit-show: error: invalid filename '$file'"
			exit 1
		fi

		if echo "$file"|egrep -q '^[^0-9A-Za-z]'
		then 
			echo "legit-show: error: invalid filename '$file'"
			exit 1

		fi
	
		if echo "$file"|egrep -q '[^0-9A-Za-z\._\-]'
		then 
			echo "legit-show: error: invalid filename '$file'"
			exit 1

		fi

		exist=`find $indexdir -name $file`
		if [ "$exist" = "" ]
		then

			echo "legit-show: error: '$file' not found in index"

			exit 1
		else
			cat $indexdir/$file
		fi
		exit 0
	fi

	if echo "$version" |egrep -q '[^0-9]'
	then
		echo "legit-show: error: unknown commit '$version'"
		exit 1
	fi
	
	if [ $version -gt $lastestversion ]
	then
		echo "legit-show: error: unknown commit '$version'"
		exit 1
	fi
	
#check file 
	if [ "$file" = "" ]
	then
		echo "legit-show: error: invalid filename '$file'"
		exit 1
	fi

	if echo "$file"|egrep -q '^[^0-9A-Za-z]'
	then 
		echo "legit-show: error: invalid filename '$file'"
		exit 1

	fi
	
	if echo "$file"|egrep -q '[^0-9A-Za-z\._\-]'
	then 
		echo "legit-show: error: invalid filename '$file'"
		exit 1

	fi
	
	exist=`find $place -name $file+$version`
	#echo "$exist"
	if [ "$exist" = "" ]
	then
		echo "legit-show: error: '$file' not found in commit $version"
		exit 1
	else
		cat $place/$file+$version
	fi
	
else
	echo "legit-show: error: invalid object "$1""
fi









